service: aws-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iam:
    role: 
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource: 
            - arn:aws:dynamodb:us-east-1:037911454825:table/TableIaas

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/itemInsert.insertItem
    events:
      - httpApi:
          path: /item
          method: post
  listItem:
    handler: src/itemList.listItem
    events:
      - httpApi:
          path: /item
          method: get
  selectItem:
    handler: src/itemSelect.selectItem
    events:
      - httpApi:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/itemUpdate.updateItem
    events:
      - httpApi:
          path: /item/{id}
          method: put
  deleteItem:
    handler: src/itemDelete.deleteItem
    events:
      - httpApi:
          path: /item/{id}
          method: delete

resources:
  Resources:
    TableIaas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TableIaas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
